# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/santourh/abstract-vm-32bits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/santourh/abstract-vm-32bits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/santourh/abstract-vm-32bits/CMakeFiles /home/santourh/abstract-vm-32bits//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/santourh/abstract-vm-32bits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abstract-vm-16bits

# Build rule for target.
abstract-vm-16bits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 abstract-vm-16bits
.PHONY : abstract-vm-16bits

# fast build rule for target.
abstract-vm-16bits/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/build
.PHONY : abstract-vm-16bits/fast

generated-sources/VMGrammarBaseListener.o: generated-sources/VMGrammarBaseListener.cpp.o
.PHONY : generated-sources/VMGrammarBaseListener.o

# target to build an object file
generated-sources/VMGrammarBaseListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseListener.cpp.o
.PHONY : generated-sources/VMGrammarBaseListener.cpp.o

generated-sources/VMGrammarBaseListener.i: generated-sources/VMGrammarBaseListener.cpp.i
.PHONY : generated-sources/VMGrammarBaseListener.i

# target to preprocess a source file
generated-sources/VMGrammarBaseListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseListener.cpp.i
.PHONY : generated-sources/VMGrammarBaseListener.cpp.i

generated-sources/VMGrammarBaseListener.s: generated-sources/VMGrammarBaseListener.cpp.s
.PHONY : generated-sources/VMGrammarBaseListener.s

# target to generate assembly for a file
generated-sources/VMGrammarBaseListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseListener.cpp.s
.PHONY : generated-sources/VMGrammarBaseListener.cpp.s

generated-sources/VMGrammarBaseVisitor.o: generated-sources/VMGrammarBaseVisitor.cpp.o
.PHONY : generated-sources/VMGrammarBaseVisitor.o

# target to build an object file
generated-sources/VMGrammarBaseVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseVisitor.cpp.o
.PHONY : generated-sources/VMGrammarBaseVisitor.cpp.o

generated-sources/VMGrammarBaseVisitor.i: generated-sources/VMGrammarBaseVisitor.cpp.i
.PHONY : generated-sources/VMGrammarBaseVisitor.i

# target to preprocess a source file
generated-sources/VMGrammarBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseVisitor.cpp.i
.PHONY : generated-sources/VMGrammarBaseVisitor.cpp.i

generated-sources/VMGrammarBaseVisitor.s: generated-sources/VMGrammarBaseVisitor.cpp.s
.PHONY : generated-sources/VMGrammarBaseVisitor.s

# target to generate assembly for a file
generated-sources/VMGrammarBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseVisitor.cpp.s
.PHONY : generated-sources/VMGrammarBaseVisitor.cpp.s

generated-sources/VMGrammarLexer.o: generated-sources/VMGrammarLexer.cpp.o
.PHONY : generated-sources/VMGrammarLexer.o

# target to build an object file
generated-sources/VMGrammarLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarLexer.cpp.o
.PHONY : generated-sources/VMGrammarLexer.cpp.o

generated-sources/VMGrammarLexer.i: generated-sources/VMGrammarLexer.cpp.i
.PHONY : generated-sources/VMGrammarLexer.i

# target to preprocess a source file
generated-sources/VMGrammarLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarLexer.cpp.i
.PHONY : generated-sources/VMGrammarLexer.cpp.i

generated-sources/VMGrammarLexer.s: generated-sources/VMGrammarLexer.cpp.s
.PHONY : generated-sources/VMGrammarLexer.s

# target to generate assembly for a file
generated-sources/VMGrammarLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarLexer.cpp.s
.PHONY : generated-sources/VMGrammarLexer.cpp.s

generated-sources/VMGrammarListener.o: generated-sources/VMGrammarListener.cpp.o
.PHONY : generated-sources/VMGrammarListener.o

# target to build an object file
generated-sources/VMGrammarListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarListener.cpp.o
.PHONY : generated-sources/VMGrammarListener.cpp.o

generated-sources/VMGrammarListener.i: generated-sources/VMGrammarListener.cpp.i
.PHONY : generated-sources/VMGrammarListener.i

# target to preprocess a source file
generated-sources/VMGrammarListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarListener.cpp.i
.PHONY : generated-sources/VMGrammarListener.cpp.i

generated-sources/VMGrammarListener.s: generated-sources/VMGrammarListener.cpp.s
.PHONY : generated-sources/VMGrammarListener.s

# target to generate assembly for a file
generated-sources/VMGrammarListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarListener.cpp.s
.PHONY : generated-sources/VMGrammarListener.cpp.s

generated-sources/VMGrammarParser.o: generated-sources/VMGrammarParser.cpp.o
.PHONY : generated-sources/VMGrammarParser.o

# target to build an object file
generated-sources/VMGrammarParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarParser.cpp.o
.PHONY : generated-sources/VMGrammarParser.cpp.o

generated-sources/VMGrammarParser.i: generated-sources/VMGrammarParser.cpp.i
.PHONY : generated-sources/VMGrammarParser.i

# target to preprocess a source file
generated-sources/VMGrammarParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarParser.cpp.i
.PHONY : generated-sources/VMGrammarParser.cpp.i

generated-sources/VMGrammarParser.s: generated-sources/VMGrammarParser.cpp.s
.PHONY : generated-sources/VMGrammarParser.s

# target to generate assembly for a file
generated-sources/VMGrammarParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarParser.cpp.s
.PHONY : generated-sources/VMGrammarParser.cpp.s

generated-sources/VMGrammarVisitor.o: generated-sources/VMGrammarVisitor.cpp.o
.PHONY : generated-sources/VMGrammarVisitor.o

# target to build an object file
generated-sources/VMGrammarVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarVisitor.cpp.o
.PHONY : generated-sources/VMGrammarVisitor.cpp.o

generated-sources/VMGrammarVisitor.i: generated-sources/VMGrammarVisitor.cpp.i
.PHONY : generated-sources/VMGrammarVisitor.i

# target to preprocess a source file
generated-sources/VMGrammarVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarVisitor.cpp.i
.PHONY : generated-sources/VMGrammarVisitor.cpp.i

generated-sources/VMGrammarVisitor.s: generated-sources/VMGrammarVisitor.cpp.s
.PHONY : generated-sources/VMGrammarVisitor.s

# target to generate assembly for a file
generated-sources/VMGrammarVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarVisitor.cpp.s
.PHONY : generated-sources/VMGrammarVisitor.cpp.s

src/VM.o: src/VM.cpp.o
.PHONY : src/VM.o

# target to build an object file
src/VM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VM.cpp.o
.PHONY : src/VM.cpp.o

src/VM.i: src/VM.cpp.i
.PHONY : src/VM.i

# target to preprocess a source file
src/VM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VM.cpp.i
.PHONY : src/VM.cpp.i

src/VM.s: src/VM.cpp.s
.PHONY : src/VM.s

# target to generate assembly for a file
src/VM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VM.cpp.s
.PHONY : src/VM.cpp.s

src/VMListener.o: src/VMListener.cpp.o
.PHONY : src/VMListener.o

# target to build an object file
src/VMListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VMListener.cpp.o
.PHONY : src/VMListener.cpp.o

src/VMListener.i: src/VMListener.cpp.i
.PHONY : src/VMListener.i

# target to preprocess a source file
src/VMListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VMListener.cpp.i
.PHONY : src/VMListener.cpp.i

src/VMListener.s: src/VMListener.cpp.s
.PHONY : src/VMListener.s

# target to generate assembly for a file
src/VMListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VMListener.cpp.s
.PHONY : src/VMListener.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... abstract-vm-16bits"
	@echo "... generated-sources/VMGrammarBaseListener.o"
	@echo "... generated-sources/VMGrammarBaseListener.i"
	@echo "... generated-sources/VMGrammarBaseListener.s"
	@echo "... generated-sources/VMGrammarBaseVisitor.o"
	@echo "... generated-sources/VMGrammarBaseVisitor.i"
	@echo "... generated-sources/VMGrammarBaseVisitor.s"
	@echo "... generated-sources/VMGrammarLexer.o"
	@echo "... generated-sources/VMGrammarLexer.i"
	@echo "... generated-sources/VMGrammarLexer.s"
	@echo "... generated-sources/VMGrammarListener.o"
	@echo "... generated-sources/VMGrammarListener.i"
	@echo "... generated-sources/VMGrammarListener.s"
	@echo "... generated-sources/VMGrammarParser.o"
	@echo "... generated-sources/VMGrammarParser.i"
	@echo "... generated-sources/VMGrammarParser.s"
	@echo "... generated-sources/VMGrammarVisitor.o"
	@echo "... generated-sources/VMGrammarVisitor.i"
	@echo "... generated-sources/VMGrammarVisitor.s"
	@echo "... src/VM.o"
	@echo "... src/VM.i"
	@echo "... src/VM.s"
	@echo "... src/VMListener.o"
	@echo "... src/VMListener.i"
	@echo "... src/VMListener.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

