# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/santourh/abstract-vm-32bits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/santourh/abstract-vm-32bits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/santourh/abstract-vm-32bits/CMakeFiles /home/santourh/abstract-vm-32bits//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/santourh/abstract-vm-32bits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/santourh/abstract-vm-32bits/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abstract-vm-16bits

# Build rule for target.
abstract-vm-16bits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 abstract-vm-16bits
.PHONY : abstract-vm-16bits

# fast build rule for target.
abstract-vm-16bits/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/build
.PHONY : abstract-vm-16bits/fast

generated-sources/VMGrammarBaseListener.o: generated-sources/VMGrammarBaseListener.cpp.o
.PHONY : generated-sources/VMGrammarBaseListener.o

# target to build an object file
generated-sources/VMGrammarBaseListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseListener.cpp.o
.PHONY : generated-sources/VMGrammarBaseListener.cpp.o

generated-sources/VMGrammarBaseListener.i: generated-sources/VMGrammarBaseListener.cpp.i
.PHONY : generated-sources/VMGrammarBaseListener.i

# target to preprocess a source file
generated-sources/VMGrammarBaseListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseListener.cpp.i
.PHONY : generated-sources/VMGrammarBaseListener.cpp.i

generated-sources/VMGrammarBaseListener.s: generated-sources/VMGrammarBaseListener.cpp.s
.PHONY : generated-sources/VMGrammarBaseListener.s

# target to generate assembly for a file
generated-sources/VMGrammarBaseListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseListener.cpp.s
.PHONY : generated-sources/VMGrammarBaseListener.cpp.s

generated-sources/VMGrammarBaseVisitor.o: generated-sources/VMGrammarBaseVisitor.cpp.o
.PHONY : generated-sources/VMGrammarBaseVisitor.o

# target to build an object file
generated-sources/VMGrammarBaseVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseVisitor.cpp.o
.PHONY : generated-sources/VMGrammarBaseVisitor.cpp.o

generated-sources/VMGrammarBaseVisitor.i: generated-sources/VMGrammarBaseVisitor.cpp.i
.PHONY : generated-sources/VMGrammarBaseVisitor.i

# target to preprocess a source file
generated-sources/VMGrammarBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseVisitor.cpp.i
.PHONY : generated-sources/VMGrammarBaseVisitor.cpp.i

generated-sources/VMGrammarBaseVisitor.s: generated-sources/VMGrammarBaseVisitor.cpp.s
.PHONY : generated-sources/VMGrammarBaseVisitor.s

# target to generate assembly for a file
generated-sources/VMGrammarBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarBaseVisitor.cpp.s
.PHONY : generated-sources/VMGrammarBaseVisitor.cpp.s

generated-sources/VMGrammarLexer.o: generated-sources/VMGrammarLexer.cpp.o
.PHONY : generated-sources/VMGrammarLexer.o

# target to build an object file
generated-sources/VMGrammarLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarLexer.cpp.o
.PHONY : generated-sources/VMGrammarLexer.cpp.o

generated-sources/VMGrammarLexer.i: generated-sources/VMGrammarLexer.cpp.i
.PHONY : generated-sources/VMGrammarLexer.i

# target to preprocess a source file
generated-sources/VMGrammarLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarLexer.cpp.i
.PHONY : generated-sources/VMGrammarLexer.cpp.i

generated-sources/VMGrammarLexer.s: generated-sources/VMGrammarLexer.cpp.s
.PHONY : generated-sources/VMGrammarLexer.s

# target to generate assembly for a file
generated-sources/VMGrammarLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarLexer.cpp.s
.PHONY : generated-sources/VMGrammarLexer.cpp.s

generated-sources/VMGrammarListener.o: generated-sources/VMGrammarListener.cpp.o
.PHONY : generated-sources/VMGrammarListener.o

# target to build an object file
generated-sources/VMGrammarListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarListener.cpp.o
.PHONY : generated-sources/VMGrammarListener.cpp.o

generated-sources/VMGrammarListener.i: generated-sources/VMGrammarListener.cpp.i
.PHONY : generated-sources/VMGrammarListener.i

# target to preprocess a source file
generated-sources/VMGrammarListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarListener.cpp.i
.PHONY : generated-sources/VMGrammarListener.cpp.i

generated-sources/VMGrammarListener.s: generated-sources/VMGrammarListener.cpp.s
.PHONY : generated-sources/VMGrammarListener.s

# target to generate assembly for a file
generated-sources/VMGrammarListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarListener.cpp.s
.PHONY : generated-sources/VMGrammarListener.cpp.s

generated-sources/VMGrammarParser.o: generated-sources/VMGrammarParser.cpp.o
.PHONY : generated-sources/VMGrammarParser.o

# target to build an object file
generated-sources/VMGrammarParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarParser.cpp.o
.PHONY : generated-sources/VMGrammarParser.cpp.o

generated-sources/VMGrammarParser.i: generated-sources/VMGrammarParser.cpp.i
.PHONY : generated-sources/VMGrammarParser.i

# target to preprocess a source file
generated-sources/VMGrammarParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarParser.cpp.i
.PHONY : generated-sources/VMGrammarParser.cpp.i

generated-sources/VMGrammarParser.s: generated-sources/VMGrammarParser.cpp.s
.PHONY : generated-sources/VMGrammarParser.s

# target to generate assembly for a file
generated-sources/VMGrammarParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarParser.cpp.s
.PHONY : generated-sources/VMGrammarParser.cpp.s

generated-sources/VMGrammarVisitor.o: generated-sources/VMGrammarVisitor.cpp.o
.PHONY : generated-sources/VMGrammarVisitor.o

# target to build an object file
generated-sources/VMGrammarVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarVisitor.cpp.o
.PHONY : generated-sources/VMGrammarVisitor.cpp.o

generated-sources/VMGrammarVisitor.i: generated-sources/VMGrammarVisitor.cpp.i
.PHONY : generated-sources/VMGrammarVisitor.i

# target to preprocess a source file
generated-sources/VMGrammarVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarVisitor.cpp.i
.PHONY : generated-sources/VMGrammarVisitor.cpp.i

generated-sources/VMGrammarVisitor.s: generated-sources/VMGrammarVisitor.cpp.s
.PHONY : generated-sources/VMGrammarVisitor.s

# target to generate assembly for a file
generated-sources/VMGrammarVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/generated-sources/VMGrammarVisitor.cpp.s
.PHONY : generated-sources/VMGrammarVisitor.cpp.s

src/Program.o: src/Program.cpp.o
.PHONY : src/Program.o

# target to build an object file
src/Program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/Program.cpp.o
.PHONY : src/Program.cpp.o

src/Program.i: src/Program.cpp.i
.PHONY : src/Program.i

# target to preprocess a source file
src/Program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/Program.cpp.i
.PHONY : src/Program.cpp.i

src/Program.s: src/Program.cpp.s
.PHONY : src/Program.s

# target to generate assembly for a file
src/Program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/Program.cpp.s
.PHONY : src/Program.cpp.s

src/VM.o: src/VM.cpp.o
.PHONY : src/VM.o

# target to build an object file
src/VM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VM.cpp.o
.PHONY : src/VM.cpp.o

src/VM.i: src/VM.cpp.i
.PHONY : src/VM.i

# target to preprocess a source file
src/VM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VM.cpp.i
.PHONY : src/VM.cpp.i

src/VM.s: src/VM.cpp.s
.PHONY : src/VM.s

# target to generate assembly for a file
src/VM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VM.cpp.s
.PHONY : src/VM.cpp.s

src/VMListener.o: src/VMListener.cpp.o
.PHONY : src/VMListener.o

# target to build an object file
src/VMListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VMListener.cpp.o
.PHONY : src/VMListener.cpp.o

src/VMListener.i: src/VMListener.cpp.i
.PHONY : src/VMListener.i

# target to preprocess a source file
src/VMListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VMListener.cpp.i
.PHONY : src/VMListener.cpp.i

src/VMListener.s: src/VMListener.cpp.s
.PHONY : src/VMListener.s

# target to generate assembly for a file
src/VMListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/VMListener.cpp.s
.PHONY : src/VMListener.cpp.s

src/instructions/ADD.o: src/instructions/ADD.cpp.o
.PHONY : src/instructions/ADD.o

# target to build an object file
src/instructions/ADD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ADD.cpp.o
.PHONY : src/instructions/ADD.cpp.o

src/instructions/ADD.i: src/instructions/ADD.cpp.i
.PHONY : src/instructions/ADD.i

# target to preprocess a source file
src/instructions/ADD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ADD.cpp.i
.PHONY : src/instructions/ADD.cpp.i

src/instructions/ADD.s: src/instructions/ADD.cpp.s
.PHONY : src/instructions/ADD.s

# target to generate assembly for a file
src/instructions/ADD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ADD.cpp.s
.PHONY : src/instructions/ADD.cpp.s

src/instructions/ADDSP.o: src/instructions/ADDSP.cpp.o
.PHONY : src/instructions/ADDSP.o

# target to build an object file
src/instructions/ADDSP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ADDSP.cpp.o
.PHONY : src/instructions/ADDSP.cpp.o

src/instructions/ADDSP.i: src/instructions/ADDSP.cpp.i
.PHONY : src/instructions/ADDSP.i

# target to preprocess a source file
src/instructions/ADDSP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ADDSP.cpp.i
.PHONY : src/instructions/ADDSP.cpp.i

src/instructions/ADDSP.s: src/instructions/ADDSP.cpp.s
.PHONY : src/instructions/ADDSP.s

# target to generate assembly for a file
src/instructions/ADDSP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ADDSP.cpp.s
.PHONY : src/instructions/ADDSP.cpp.s

src/instructions/BRA.o: src/instructions/BRA.cpp.o
.PHONY : src/instructions/BRA.o

# target to build an object file
src/instructions/BRA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/BRA.cpp.o
.PHONY : src/instructions/BRA.cpp.o

src/instructions/BRA.i: src/instructions/BRA.cpp.i
.PHONY : src/instructions/BRA.i

# target to preprocess a source file
src/instructions/BRA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/BRA.cpp.i
.PHONY : src/instructions/BRA.cpp.i

src/instructions/BRA.s: src/instructions/BRA.cpp.s
.PHONY : src/instructions/BRA.s

# target to generate assembly for a file
src/instructions/BRA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/BRA.cpp.s
.PHONY : src/instructions/BRA.cpp.s

src/instructions/BSR.o: src/instructions/BSR.cpp.o
.PHONY : src/instructions/BSR.o

# target to build an object file
src/instructions/BSR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/BSR.cpp.o
.PHONY : src/instructions/BSR.cpp.o

src/instructions/BSR.i: src/instructions/BSR.cpp.i
.PHONY : src/instructions/BSR.i

# target to preprocess a source file
src/instructions/BSR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/BSR.cpp.i
.PHONY : src/instructions/BSR.cpp.i

src/instructions/BSR.s: src/instructions/BSR.cpp.s
.PHONY : src/instructions/BSR.s

# target to generate assembly for a file
src/instructions/BSR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/BSR.cpp.s
.PHONY : src/instructions/BSR.cpp.s

src/instructions/Bcc/BEQ.o: src/instructions/Bcc/BEQ.cpp.o
.PHONY : src/instructions/Bcc/BEQ.o

# target to build an object file
src/instructions/Bcc/BEQ.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BEQ.cpp.o
.PHONY : src/instructions/Bcc/BEQ.cpp.o

src/instructions/Bcc/BEQ.i: src/instructions/Bcc/BEQ.cpp.i
.PHONY : src/instructions/Bcc/BEQ.i

# target to preprocess a source file
src/instructions/Bcc/BEQ.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BEQ.cpp.i
.PHONY : src/instructions/Bcc/BEQ.cpp.i

src/instructions/Bcc/BEQ.s: src/instructions/Bcc/BEQ.cpp.s
.PHONY : src/instructions/Bcc/BEQ.s

# target to generate assembly for a file
src/instructions/Bcc/BEQ.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BEQ.cpp.s
.PHONY : src/instructions/Bcc/BEQ.cpp.s

src/instructions/Bcc/BGE.o: src/instructions/Bcc/BGE.cpp.o
.PHONY : src/instructions/Bcc/BGE.o

# target to build an object file
src/instructions/Bcc/BGE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BGE.cpp.o
.PHONY : src/instructions/Bcc/BGE.cpp.o

src/instructions/Bcc/BGE.i: src/instructions/Bcc/BGE.cpp.i
.PHONY : src/instructions/Bcc/BGE.i

# target to preprocess a source file
src/instructions/Bcc/BGE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BGE.cpp.i
.PHONY : src/instructions/Bcc/BGE.cpp.i

src/instructions/Bcc/BGE.s: src/instructions/Bcc/BGE.cpp.s
.PHONY : src/instructions/Bcc/BGE.s

# target to generate assembly for a file
src/instructions/Bcc/BGE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BGE.cpp.s
.PHONY : src/instructions/Bcc/BGE.cpp.s

src/instructions/Bcc/BGT.o: src/instructions/Bcc/BGT.cpp.o
.PHONY : src/instructions/Bcc/BGT.o

# target to build an object file
src/instructions/Bcc/BGT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BGT.cpp.o
.PHONY : src/instructions/Bcc/BGT.cpp.o

src/instructions/Bcc/BGT.i: src/instructions/Bcc/BGT.cpp.i
.PHONY : src/instructions/Bcc/BGT.i

# target to preprocess a source file
src/instructions/Bcc/BGT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BGT.cpp.i
.PHONY : src/instructions/Bcc/BGT.cpp.i

src/instructions/Bcc/BGT.s: src/instructions/Bcc/BGT.cpp.s
.PHONY : src/instructions/Bcc/BGT.s

# target to generate assembly for a file
src/instructions/Bcc/BGT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BGT.cpp.s
.PHONY : src/instructions/Bcc/BGT.cpp.s

src/instructions/Bcc/BLE.o: src/instructions/Bcc/BLE.cpp.o
.PHONY : src/instructions/Bcc/BLE.o

# target to build an object file
src/instructions/Bcc/BLE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BLE.cpp.o
.PHONY : src/instructions/Bcc/BLE.cpp.o

src/instructions/Bcc/BLE.i: src/instructions/Bcc/BLE.cpp.i
.PHONY : src/instructions/Bcc/BLE.i

# target to preprocess a source file
src/instructions/Bcc/BLE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BLE.cpp.i
.PHONY : src/instructions/Bcc/BLE.cpp.i

src/instructions/Bcc/BLE.s: src/instructions/Bcc/BLE.cpp.s
.PHONY : src/instructions/Bcc/BLE.s

# target to generate assembly for a file
src/instructions/Bcc/BLE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BLE.cpp.s
.PHONY : src/instructions/Bcc/BLE.cpp.s

src/instructions/Bcc/BLT.o: src/instructions/Bcc/BLT.cpp.o
.PHONY : src/instructions/Bcc/BLT.o

# target to build an object file
src/instructions/Bcc/BLT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BLT.cpp.o
.PHONY : src/instructions/Bcc/BLT.cpp.o

src/instructions/Bcc/BLT.i: src/instructions/Bcc/BLT.cpp.i
.PHONY : src/instructions/Bcc/BLT.i

# target to preprocess a source file
src/instructions/Bcc/BLT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BLT.cpp.i
.PHONY : src/instructions/Bcc/BLT.cpp.i

src/instructions/Bcc/BLT.s: src/instructions/Bcc/BLT.cpp.s
.PHONY : src/instructions/Bcc/BLT.s

# target to generate assembly for a file
src/instructions/Bcc/BLT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BLT.cpp.s
.PHONY : src/instructions/Bcc/BLT.cpp.s

src/instructions/Bcc/BNE.o: src/instructions/Bcc/BNE.cpp.o
.PHONY : src/instructions/Bcc/BNE.o

# target to build an object file
src/instructions/Bcc/BNE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BNE.cpp.o
.PHONY : src/instructions/Bcc/BNE.cpp.o

src/instructions/Bcc/BNE.i: src/instructions/Bcc/BNE.cpp.i
.PHONY : src/instructions/Bcc/BNE.i

# target to preprocess a source file
src/instructions/Bcc/BNE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BNE.cpp.i
.PHONY : src/instructions/Bcc/BNE.cpp.i

src/instructions/Bcc/BNE.s: src/instructions/Bcc/BNE.cpp.s
.PHONY : src/instructions/Bcc/BNE.s

# target to generate assembly for a file
src/instructions/Bcc/BNE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BNE.cpp.s
.PHONY : src/instructions/Bcc/BNE.cpp.s

src/instructions/Bcc/BOV.o: src/instructions/Bcc/BOV.cpp.o
.PHONY : src/instructions/Bcc/BOV.o

# target to build an object file
src/instructions/Bcc/BOV.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BOV.cpp.o
.PHONY : src/instructions/Bcc/BOV.cpp.o

src/instructions/Bcc/BOV.i: src/instructions/Bcc/BOV.cpp.i
.PHONY : src/instructions/Bcc/BOV.i

# target to preprocess a source file
src/instructions/Bcc/BOV.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BOV.cpp.i
.PHONY : src/instructions/Bcc/BOV.cpp.i

src/instructions/Bcc/BOV.s: src/instructions/Bcc/BOV.cpp.s
.PHONY : src/instructions/Bcc/BOV.s

# target to generate assembly for a file
src/instructions/Bcc/BOV.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Bcc/BOV.cpp.s
.PHONY : src/instructions/Bcc/BOV.cpp.s

src/instructions/CMP.o: src/instructions/CMP.cpp.o
.PHONY : src/instructions/CMP.o

# target to build an object file
src/instructions/CMP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/CMP.cpp.o
.PHONY : src/instructions/CMP.cpp.o

src/instructions/CMP.i: src/instructions/CMP.cpp.i
.PHONY : src/instructions/CMP.i

# target to preprocess a source file
src/instructions/CMP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/CMP.cpp.i
.PHONY : src/instructions/CMP.cpp.i

src/instructions/CMP.s: src/instructions/CMP.cpp.s
.PHONY : src/instructions/CMP.s

# target to generate assembly for a file
src/instructions/CMP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/CMP.cpp.s
.PHONY : src/instructions/CMP.cpp.s

src/instructions/DIV.o: src/instructions/DIV.cpp.o
.PHONY : src/instructions/DIV.o

# target to build an object file
src/instructions/DIV.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/DIV.cpp.o
.PHONY : src/instructions/DIV.cpp.o

src/instructions/DIV.i: src/instructions/DIV.cpp.i
.PHONY : src/instructions/DIV.i

# target to preprocess a source file
src/instructions/DIV.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/DIV.cpp.i
.PHONY : src/instructions/DIV.cpp.i

src/instructions/DIV.s: src/instructions/DIV.cpp.s
.PHONY : src/instructions/DIV.s

# target to generate assembly for a file
src/instructions/DIV.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/DIV.cpp.s
.PHONY : src/instructions/DIV.cpp.s

src/instructions/ERROR.o: src/instructions/ERROR.cpp.o
.PHONY : src/instructions/ERROR.o

# target to build an object file
src/instructions/ERROR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ERROR.cpp.o
.PHONY : src/instructions/ERROR.cpp.o

src/instructions/ERROR.i: src/instructions/ERROR.cpp.i
.PHONY : src/instructions/ERROR.i

# target to preprocess a source file
src/instructions/ERROR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ERROR.cpp.i
.PHONY : src/instructions/ERROR.cpp.i

src/instructions/ERROR.s: src/instructions/ERROR.cpp.s
.PHONY : src/instructions/ERROR.s

# target to generate assembly for a file
src/instructions/ERROR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/ERROR.cpp.s
.PHONY : src/instructions/ERROR.cpp.s

src/instructions/HALT.o: src/instructions/HALT.cpp.o
.PHONY : src/instructions/HALT.o

# target to build an object file
src/instructions/HALT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/HALT.cpp.o
.PHONY : src/instructions/HALT.cpp.o

src/instructions/HALT.i: src/instructions/HALT.cpp.i
.PHONY : src/instructions/HALT.i

# target to preprocess a source file
src/instructions/HALT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/HALT.cpp.i
.PHONY : src/instructions/HALT.cpp.i

src/instructions/HALT.s: src/instructions/HALT.cpp.s
.PHONY : src/instructions/HALT.s

# target to generate assembly for a file
src/instructions/HALT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/HALT.cpp.s
.PHONY : src/instructions/HALT.cpp.s

src/instructions/IInstruction.o: src/instructions/IInstruction.cpp.o
.PHONY : src/instructions/IInstruction.o

# target to build an object file
src/instructions/IInstruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/IInstruction.cpp.o
.PHONY : src/instructions/IInstruction.cpp.o

src/instructions/IInstruction.i: src/instructions/IInstruction.cpp.i
.PHONY : src/instructions/IInstruction.i

# target to preprocess a source file
src/instructions/IInstruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/IInstruction.cpp.i
.PHONY : src/instructions/IInstruction.cpp.i

src/instructions/IInstruction.s: src/instructions/IInstruction.cpp.s
.PHONY : src/instructions/IInstruction.s

# target to generate assembly for a file
src/instructions/IInstruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/IInstruction.cpp.s
.PHONY : src/instructions/IInstruction.cpp.s

src/instructions/LEA.o: src/instructions/LEA.cpp.o
.PHONY : src/instructions/LEA.o

# target to build an object file
src/instructions/LEA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/LEA.cpp.o
.PHONY : src/instructions/LEA.cpp.o

src/instructions/LEA.i: src/instructions/LEA.cpp.i
.PHONY : src/instructions/LEA.i

# target to preprocess a source file
src/instructions/LEA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/LEA.cpp.i
.PHONY : src/instructions/LEA.cpp.i

src/instructions/LEA.s: src/instructions/LEA.cpp.s
.PHONY : src/instructions/LEA.s

# target to generate assembly for a file
src/instructions/LEA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/LEA.cpp.s
.PHONY : src/instructions/LEA.cpp.s

src/instructions/LOAD.o: src/instructions/LOAD.cpp.o
.PHONY : src/instructions/LOAD.o

# target to build an object file
src/instructions/LOAD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/LOAD.cpp.o
.PHONY : src/instructions/LOAD.cpp.o

src/instructions/LOAD.i: src/instructions/LOAD.cpp.i
.PHONY : src/instructions/LOAD.i

# target to preprocess a source file
src/instructions/LOAD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/LOAD.cpp.i
.PHONY : src/instructions/LOAD.cpp.i

src/instructions/LOAD.s: src/instructions/LOAD.cpp.s
.PHONY : src/instructions/LOAD.s

# target to generate assembly for a file
src/instructions/LOAD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/LOAD.cpp.s
.PHONY : src/instructions/LOAD.cpp.s

src/instructions/Label.o: src/instructions/Label.cpp.o
.PHONY : src/instructions/Label.o

# target to build an object file
src/instructions/Label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Label.cpp.o
.PHONY : src/instructions/Label.cpp.o

src/instructions/Label.i: src/instructions/Label.cpp.i
.PHONY : src/instructions/Label.i

# target to preprocess a source file
src/instructions/Label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Label.cpp.i
.PHONY : src/instructions/Label.cpp.i

src/instructions/Label.s: src/instructions/Label.cpp.s
.PHONY : src/instructions/Label.s

# target to generate assembly for a file
src/instructions/Label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Label.cpp.s
.PHONY : src/instructions/Label.cpp.s

src/instructions/MUL.o: src/instructions/MUL.cpp.o
.PHONY : src/instructions/MUL.o

# target to build an object file
src/instructions/MUL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/MUL.cpp.o
.PHONY : src/instructions/MUL.cpp.o

src/instructions/MUL.i: src/instructions/MUL.cpp.i
.PHONY : src/instructions/MUL.i

# target to preprocess a source file
src/instructions/MUL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/MUL.cpp.i
.PHONY : src/instructions/MUL.cpp.i

src/instructions/MUL.s: src/instructions/MUL.cpp.s
.PHONY : src/instructions/MUL.s

# target to generate assembly for a file
src/instructions/MUL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/MUL.cpp.s
.PHONY : src/instructions/MUL.cpp.s

src/instructions/NEW.o: src/instructions/NEW.cpp.o
.PHONY : src/instructions/NEW.o

# target to build an object file
src/instructions/NEW.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/NEW.cpp.o
.PHONY : src/instructions/NEW.cpp.o

src/instructions/NEW.i: src/instructions/NEW.cpp.i
.PHONY : src/instructions/NEW.i

# target to preprocess a source file
src/instructions/NEW.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/NEW.cpp.i
.PHONY : src/instructions/NEW.cpp.i

src/instructions/NEW.s: src/instructions/NEW.cpp.s
.PHONY : src/instructions/NEW.s

# target to generate assembly for a file
src/instructions/NEW.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/NEW.cpp.s
.PHONY : src/instructions/NEW.cpp.s

src/instructions/OPP.o: src/instructions/OPP.cpp.o
.PHONY : src/instructions/OPP.o

# target to build an object file
src/instructions/OPP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/OPP.cpp.o
.PHONY : src/instructions/OPP.cpp.o

src/instructions/OPP.i: src/instructions/OPP.cpp.i
.PHONY : src/instructions/OPP.i

# target to preprocess a source file
src/instructions/OPP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/OPP.cpp.i
.PHONY : src/instructions/OPP.cpp.i

src/instructions/OPP.s: src/instructions/OPP.cpp.s
.PHONY : src/instructions/OPP.s

# target to generate assembly for a file
src/instructions/OPP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/OPP.cpp.s
.PHONY : src/instructions/OPP.cpp.s

src/instructions/PEA.o: src/instructions/PEA.cpp.o
.PHONY : src/instructions/PEA.o

# target to build an object file
src/instructions/PEA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/PEA.cpp.o
.PHONY : src/instructions/PEA.cpp.o

src/instructions/PEA.i: src/instructions/PEA.cpp.i
.PHONY : src/instructions/PEA.i

# target to preprocess a source file
src/instructions/PEA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/PEA.cpp.i
.PHONY : src/instructions/PEA.cpp.i

src/instructions/PEA.s: src/instructions/PEA.cpp.s
.PHONY : src/instructions/PEA.s

# target to generate assembly for a file
src/instructions/PEA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/PEA.cpp.s
.PHONY : src/instructions/PEA.cpp.s

src/instructions/POP.o: src/instructions/POP.cpp.o
.PHONY : src/instructions/POP.o

# target to build an object file
src/instructions/POP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/POP.cpp.o
.PHONY : src/instructions/POP.cpp.o

src/instructions/POP.i: src/instructions/POP.cpp.i
.PHONY : src/instructions/POP.i

# target to preprocess a source file
src/instructions/POP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/POP.cpp.i
.PHONY : src/instructions/POP.cpp.i

src/instructions/POP.s: src/instructions/POP.cpp.s
.PHONY : src/instructions/POP.s

# target to generate assembly for a file
src/instructions/POP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/POP.cpp.s
.PHONY : src/instructions/POP.cpp.s

src/instructions/PUSH.o: src/instructions/PUSH.cpp.o
.PHONY : src/instructions/PUSH.o

# target to build an object file
src/instructions/PUSH.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/PUSH.cpp.o
.PHONY : src/instructions/PUSH.cpp.o

src/instructions/PUSH.i: src/instructions/PUSH.cpp.i
.PHONY : src/instructions/PUSH.i

# target to preprocess a source file
src/instructions/PUSH.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/PUSH.cpp.i
.PHONY : src/instructions/PUSH.cpp.i

src/instructions/PUSH.s: src/instructions/PUSH.cpp.s
.PHONY : src/instructions/PUSH.s

# target to generate assembly for a file
src/instructions/PUSH.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/PUSH.cpp.s
.PHONY : src/instructions/PUSH.cpp.s

src/instructions/QUO.o: src/instructions/QUO.cpp.o
.PHONY : src/instructions/QUO.o

# target to build an object file
src/instructions/QUO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/QUO.cpp.o
.PHONY : src/instructions/QUO.cpp.o

src/instructions/QUO.i: src/instructions/QUO.cpp.i
.PHONY : src/instructions/QUO.i

# target to preprocess a source file
src/instructions/QUO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/QUO.cpp.i
.PHONY : src/instructions/QUO.cpp.i

src/instructions/QUO.s: src/instructions/QUO.cpp.s
.PHONY : src/instructions/QUO.s

# target to generate assembly for a file
src/instructions/QUO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/QUO.cpp.s
.PHONY : src/instructions/QUO.cpp.s

src/instructions/REM.o: src/instructions/REM.cpp.o
.PHONY : src/instructions/REM.o

# target to build an object file
src/instructions/REM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/REM.cpp.o
.PHONY : src/instructions/REM.cpp.o

src/instructions/REM.i: src/instructions/REM.cpp.i
.PHONY : src/instructions/REM.i

# target to preprocess a source file
src/instructions/REM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/REM.cpp.i
.PHONY : src/instructions/REM.cpp.i

src/instructions/REM.s: src/instructions/REM.cpp.s
.PHONY : src/instructions/REM.s

# target to generate assembly for a file
src/instructions/REM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/REM.cpp.s
.PHONY : src/instructions/REM.cpp.s

src/instructions/RFLOAT.o: src/instructions/RFLOAT.cpp.o
.PHONY : src/instructions/RFLOAT.o

# target to build an object file
src/instructions/RFLOAT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RFLOAT.cpp.o
.PHONY : src/instructions/RFLOAT.cpp.o

src/instructions/RFLOAT.i: src/instructions/RFLOAT.cpp.i
.PHONY : src/instructions/RFLOAT.i

# target to preprocess a source file
src/instructions/RFLOAT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RFLOAT.cpp.i
.PHONY : src/instructions/RFLOAT.cpp.i

src/instructions/RFLOAT.s: src/instructions/RFLOAT.cpp.s
.PHONY : src/instructions/RFLOAT.s

# target to generate assembly for a file
src/instructions/RFLOAT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RFLOAT.cpp.s
.PHONY : src/instructions/RFLOAT.cpp.s

src/instructions/RINT.o: src/instructions/RINT.cpp.o
.PHONY : src/instructions/RINT.o

# target to build an object file
src/instructions/RINT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RINT.cpp.o
.PHONY : src/instructions/RINT.cpp.o

src/instructions/RINT.i: src/instructions/RINT.cpp.i
.PHONY : src/instructions/RINT.i

# target to preprocess a source file
src/instructions/RINT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RINT.cpp.i
.PHONY : src/instructions/RINT.cpp.i

src/instructions/RINT.s: src/instructions/RINT.cpp.s
.PHONY : src/instructions/RINT.s

# target to generate assembly for a file
src/instructions/RINT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RINT.cpp.s
.PHONY : src/instructions/RINT.cpp.s

src/instructions/RTS.o: src/instructions/RTS.cpp.o
.PHONY : src/instructions/RTS.o

# target to build an object file
src/instructions/RTS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RTS.cpp.o
.PHONY : src/instructions/RTS.cpp.o

src/instructions/RTS.i: src/instructions/RTS.cpp.i
.PHONY : src/instructions/RTS.i

# target to preprocess a source file
src/instructions/RTS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RTS.cpp.i
.PHONY : src/instructions/RTS.cpp.i

src/instructions/RTS.s: src/instructions/RTS.cpp.s
.PHONY : src/instructions/RTS.s

# target to generate assembly for a file
src/instructions/RTS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/RTS.cpp.s
.PHONY : src/instructions/RTS.cpp.s

src/instructions/STORE.o: src/instructions/STORE.cpp.o
.PHONY : src/instructions/STORE.o

# target to build an object file
src/instructions/STORE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/STORE.cpp.o
.PHONY : src/instructions/STORE.cpp.o

src/instructions/STORE.i: src/instructions/STORE.cpp.i
.PHONY : src/instructions/STORE.i

# target to preprocess a source file
src/instructions/STORE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/STORE.cpp.i
.PHONY : src/instructions/STORE.cpp.i

src/instructions/STORE.s: src/instructions/STORE.cpp.s
.PHONY : src/instructions/STORE.s

# target to generate assembly for a file
src/instructions/STORE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/STORE.cpp.s
.PHONY : src/instructions/STORE.cpp.s

src/instructions/SUB.o: src/instructions/SUB.cpp.o
.PHONY : src/instructions/SUB.o

# target to build an object file
src/instructions/SUB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/SUB.cpp.o
.PHONY : src/instructions/SUB.cpp.o

src/instructions/SUB.i: src/instructions/SUB.cpp.i
.PHONY : src/instructions/SUB.i

# target to preprocess a source file
src/instructions/SUB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/SUB.cpp.i
.PHONY : src/instructions/SUB.cpp.i

src/instructions/SUB.s: src/instructions/SUB.cpp.s
.PHONY : src/instructions/SUB.s

# target to generate assembly for a file
src/instructions/SUB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/SUB.cpp.s
.PHONY : src/instructions/SUB.cpp.s

src/instructions/SUBSP.o: src/instructions/SUBSP.cpp.o
.PHONY : src/instructions/SUBSP.o

# target to build an object file
src/instructions/SUBSP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/SUBSP.cpp.o
.PHONY : src/instructions/SUBSP.cpp.o

src/instructions/SUBSP.i: src/instructions/SUBSP.cpp.i
.PHONY : src/instructions/SUBSP.i

# target to preprocess a source file
src/instructions/SUBSP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/SUBSP.cpp.i
.PHONY : src/instructions/SUBSP.cpp.i

src/instructions/SUBSP.s: src/instructions/SUBSP.cpp.s
.PHONY : src/instructions/SUBSP.s

# target to generate assembly for a file
src/instructions/SUBSP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/SUBSP.cpp.s
.PHONY : src/instructions/SUBSP.cpp.s

src/instructions/Scc/SEQ.o: src/instructions/Scc/SEQ.cpp.o
.PHONY : src/instructions/Scc/SEQ.o

# target to build an object file
src/instructions/Scc/SEQ.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SEQ.cpp.o
.PHONY : src/instructions/Scc/SEQ.cpp.o

src/instructions/Scc/SEQ.i: src/instructions/Scc/SEQ.cpp.i
.PHONY : src/instructions/Scc/SEQ.i

# target to preprocess a source file
src/instructions/Scc/SEQ.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SEQ.cpp.i
.PHONY : src/instructions/Scc/SEQ.cpp.i

src/instructions/Scc/SEQ.s: src/instructions/Scc/SEQ.cpp.s
.PHONY : src/instructions/Scc/SEQ.s

# target to generate assembly for a file
src/instructions/Scc/SEQ.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SEQ.cpp.s
.PHONY : src/instructions/Scc/SEQ.cpp.s

src/instructions/Scc/SGE.o: src/instructions/Scc/SGE.cpp.o
.PHONY : src/instructions/Scc/SGE.o

# target to build an object file
src/instructions/Scc/SGE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SGE.cpp.o
.PHONY : src/instructions/Scc/SGE.cpp.o

src/instructions/Scc/SGE.i: src/instructions/Scc/SGE.cpp.i
.PHONY : src/instructions/Scc/SGE.i

# target to preprocess a source file
src/instructions/Scc/SGE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SGE.cpp.i
.PHONY : src/instructions/Scc/SGE.cpp.i

src/instructions/Scc/SGE.s: src/instructions/Scc/SGE.cpp.s
.PHONY : src/instructions/Scc/SGE.s

# target to generate assembly for a file
src/instructions/Scc/SGE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SGE.cpp.s
.PHONY : src/instructions/Scc/SGE.cpp.s

src/instructions/Scc/SGT.o: src/instructions/Scc/SGT.cpp.o
.PHONY : src/instructions/Scc/SGT.o

# target to build an object file
src/instructions/Scc/SGT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SGT.cpp.o
.PHONY : src/instructions/Scc/SGT.cpp.o

src/instructions/Scc/SGT.i: src/instructions/Scc/SGT.cpp.i
.PHONY : src/instructions/Scc/SGT.i

# target to preprocess a source file
src/instructions/Scc/SGT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SGT.cpp.i
.PHONY : src/instructions/Scc/SGT.cpp.i

src/instructions/Scc/SGT.s: src/instructions/Scc/SGT.cpp.s
.PHONY : src/instructions/Scc/SGT.s

# target to generate assembly for a file
src/instructions/Scc/SGT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SGT.cpp.s
.PHONY : src/instructions/Scc/SGT.cpp.s

src/instructions/Scc/SHL.o: src/instructions/Scc/SHL.cpp.o
.PHONY : src/instructions/Scc/SHL.o

# target to build an object file
src/instructions/Scc/SHL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SHL.cpp.o
.PHONY : src/instructions/Scc/SHL.cpp.o

src/instructions/Scc/SHL.i: src/instructions/Scc/SHL.cpp.i
.PHONY : src/instructions/Scc/SHL.i

# target to preprocess a source file
src/instructions/Scc/SHL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SHL.cpp.i
.PHONY : src/instructions/Scc/SHL.cpp.i

src/instructions/Scc/SHL.s: src/instructions/Scc/SHL.cpp.s
.PHONY : src/instructions/Scc/SHL.s

# target to generate assembly for a file
src/instructions/Scc/SHL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SHL.cpp.s
.PHONY : src/instructions/Scc/SHL.cpp.s

src/instructions/Scc/SHR.o: src/instructions/Scc/SHR.cpp.o
.PHONY : src/instructions/Scc/SHR.o

# target to build an object file
src/instructions/Scc/SHR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SHR.cpp.o
.PHONY : src/instructions/Scc/SHR.cpp.o

src/instructions/Scc/SHR.i: src/instructions/Scc/SHR.cpp.i
.PHONY : src/instructions/Scc/SHR.i

# target to preprocess a source file
src/instructions/Scc/SHR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SHR.cpp.i
.PHONY : src/instructions/Scc/SHR.cpp.i

src/instructions/Scc/SHR.s: src/instructions/Scc/SHR.cpp.s
.PHONY : src/instructions/Scc/SHR.s

# target to generate assembly for a file
src/instructions/Scc/SHR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SHR.cpp.s
.PHONY : src/instructions/Scc/SHR.cpp.s

src/instructions/Scc/SLE.o: src/instructions/Scc/SLE.cpp.o
.PHONY : src/instructions/Scc/SLE.o

# target to build an object file
src/instructions/Scc/SLE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SLE.cpp.o
.PHONY : src/instructions/Scc/SLE.cpp.o

src/instructions/Scc/SLE.i: src/instructions/Scc/SLE.cpp.i
.PHONY : src/instructions/Scc/SLE.i

# target to preprocess a source file
src/instructions/Scc/SLE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SLE.cpp.i
.PHONY : src/instructions/Scc/SLE.cpp.i

src/instructions/Scc/SLE.s: src/instructions/Scc/SLE.cpp.s
.PHONY : src/instructions/Scc/SLE.s

# target to generate assembly for a file
src/instructions/Scc/SLE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SLE.cpp.s
.PHONY : src/instructions/Scc/SLE.cpp.s

src/instructions/Scc/SLT.o: src/instructions/Scc/SLT.cpp.o
.PHONY : src/instructions/Scc/SLT.o

# target to build an object file
src/instructions/Scc/SLT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SLT.cpp.o
.PHONY : src/instructions/Scc/SLT.cpp.o

src/instructions/Scc/SLT.i: src/instructions/Scc/SLT.cpp.i
.PHONY : src/instructions/Scc/SLT.i

# target to preprocess a source file
src/instructions/Scc/SLT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SLT.cpp.i
.PHONY : src/instructions/Scc/SLT.cpp.i

src/instructions/Scc/SLT.s: src/instructions/Scc/SLT.cpp.s
.PHONY : src/instructions/Scc/SLT.s

# target to generate assembly for a file
src/instructions/Scc/SLT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SLT.cpp.s
.PHONY : src/instructions/Scc/SLT.cpp.s

src/instructions/Scc/SNE.o: src/instructions/Scc/SNE.cpp.o
.PHONY : src/instructions/Scc/SNE.o

# target to build an object file
src/instructions/Scc/SNE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SNE.cpp.o
.PHONY : src/instructions/Scc/SNE.cpp.o

src/instructions/Scc/SNE.i: src/instructions/Scc/SNE.cpp.i
.PHONY : src/instructions/Scc/SNE.i

# target to preprocess a source file
src/instructions/Scc/SNE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SNE.cpp.i
.PHONY : src/instructions/Scc/SNE.cpp.i

src/instructions/Scc/SNE.s: src/instructions/Scc/SNE.cpp.s
.PHONY : src/instructions/Scc/SNE.s

# target to generate assembly for a file
src/instructions/Scc/SNE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SNE.cpp.s
.PHONY : src/instructions/Scc/SNE.cpp.s

src/instructions/Scc/SOV.o: src/instructions/Scc/SOV.cpp.o
.PHONY : src/instructions/Scc/SOV.o

# target to build an object file
src/instructions/Scc/SOV.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SOV.cpp.o
.PHONY : src/instructions/Scc/SOV.cpp.o

src/instructions/Scc/SOV.i: src/instructions/Scc/SOV.cpp.i
.PHONY : src/instructions/Scc/SOV.i

# target to preprocess a source file
src/instructions/Scc/SOV.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SOV.cpp.i
.PHONY : src/instructions/Scc/SOV.cpp.i

src/instructions/Scc/SOV.s: src/instructions/Scc/SOV.cpp.s
.PHONY : src/instructions/Scc/SOV.s

# target to generate assembly for a file
src/instructions/Scc/SOV.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/Scc/SOV.cpp.s
.PHONY : src/instructions/Scc/SOV.cpp.s

src/instructions/TSTO.o: src/instructions/TSTO.cpp.o
.PHONY : src/instructions/TSTO.o

# target to build an object file
src/instructions/TSTO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/TSTO.cpp.o
.PHONY : src/instructions/TSTO.cpp.o

src/instructions/TSTO.i: src/instructions/TSTO.cpp.i
.PHONY : src/instructions/TSTO.i

# target to preprocess a source file
src/instructions/TSTO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/TSTO.cpp.i
.PHONY : src/instructions/TSTO.cpp.i

src/instructions/TSTO.s: src/instructions/TSTO.cpp.s
.PHONY : src/instructions/TSTO.s

# target to generate assembly for a file
src/instructions/TSTO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/TSTO.cpp.s
.PHONY : src/instructions/TSTO.cpp.s

src/instructions/WADDR.o: src/instructions/WADDR.cpp.o
.PHONY : src/instructions/WADDR.o

# target to build an object file
src/instructions/WADDR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WADDR.cpp.o
.PHONY : src/instructions/WADDR.cpp.o

src/instructions/WADDR.i: src/instructions/WADDR.cpp.i
.PHONY : src/instructions/WADDR.i

# target to preprocess a source file
src/instructions/WADDR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WADDR.cpp.i
.PHONY : src/instructions/WADDR.cpp.i

src/instructions/WADDR.s: src/instructions/WADDR.cpp.s
.PHONY : src/instructions/WADDR.s

# target to generate assembly for a file
src/instructions/WADDR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WADDR.cpp.s
.PHONY : src/instructions/WADDR.cpp.s

src/instructions/WFLOAT.o: src/instructions/WFLOAT.cpp.o
.PHONY : src/instructions/WFLOAT.o

# target to build an object file
src/instructions/WFLOAT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WFLOAT.cpp.o
.PHONY : src/instructions/WFLOAT.cpp.o

src/instructions/WFLOAT.i: src/instructions/WFLOAT.cpp.i
.PHONY : src/instructions/WFLOAT.i

# target to preprocess a source file
src/instructions/WFLOAT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WFLOAT.cpp.i
.PHONY : src/instructions/WFLOAT.cpp.i

src/instructions/WFLOAT.s: src/instructions/WFLOAT.cpp.s
.PHONY : src/instructions/WFLOAT.s

# target to generate assembly for a file
src/instructions/WFLOAT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WFLOAT.cpp.s
.PHONY : src/instructions/WFLOAT.cpp.s

src/instructions/WINT.o: src/instructions/WINT.cpp.o
.PHONY : src/instructions/WINT.o

# target to build an object file
src/instructions/WINT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WINT.cpp.o
.PHONY : src/instructions/WINT.cpp.o

src/instructions/WINT.i: src/instructions/WINT.cpp.i
.PHONY : src/instructions/WINT.i

# target to preprocess a source file
src/instructions/WINT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WINT.cpp.i
.PHONY : src/instructions/WINT.cpp.i

src/instructions/WINT.s: src/instructions/WINT.cpp.s
.PHONY : src/instructions/WINT.s

# target to generate assembly for a file
src/instructions/WINT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WINT.cpp.s
.PHONY : src/instructions/WINT.cpp.s

src/instructions/WNL.o: src/instructions/WNL.cpp.o
.PHONY : src/instructions/WNL.o

# target to build an object file
src/instructions/WNL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WNL.cpp.o
.PHONY : src/instructions/WNL.cpp.o

src/instructions/WNL.i: src/instructions/WNL.cpp.i
.PHONY : src/instructions/WNL.i

# target to preprocess a source file
src/instructions/WNL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WNL.cpp.i
.PHONY : src/instructions/WNL.cpp.i

src/instructions/WNL.s: src/instructions/WNL.cpp.s
.PHONY : src/instructions/WNL.s

# target to generate assembly for a file
src/instructions/WNL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WNL.cpp.s
.PHONY : src/instructions/WNL.cpp.s

src/instructions/WSTR.o: src/instructions/WSTR.cpp.o
.PHONY : src/instructions/WSTR.o

# target to build an object file
src/instructions/WSTR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WSTR.cpp.o
.PHONY : src/instructions/WSTR.cpp.o

src/instructions/WSTR.i: src/instructions/WSTR.cpp.i
.PHONY : src/instructions/WSTR.i

# target to preprocess a source file
src/instructions/WSTR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WSTR.cpp.i
.PHONY : src/instructions/WSTR.cpp.i

src/instructions/WSTR.s: src/instructions/WSTR.cpp.s
.PHONY : src/instructions/WSTR.s

# target to generate assembly for a file
src/instructions/WSTR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/instructions/WSTR.cpp.s
.PHONY : src/instructions/WSTR.cpp.s

src/machine/EnvRegisters.o: src/machine/EnvRegisters.cpp.o
.PHONY : src/machine/EnvRegisters.o

# target to build an object file
src/machine/EnvRegisters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/EnvRegisters.cpp.o
.PHONY : src/machine/EnvRegisters.cpp.o

src/machine/EnvRegisters.i: src/machine/EnvRegisters.cpp.i
.PHONY : src/machine/EnvRegisters.i

# target to preprocess a source file
src/machine/EnvRegisters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/EnvRegisters.cpp.i
.PHONY : src/machine/EnvRegisters.cpp.i

src/machine/EnvRegisters.s: src/machine/EnvRegisters.cpp.s
.PHONY : src/machine/EnvRegisters.s

# target to generate assembly for a file
src/machine/EnvRegisters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/EnvRegisters.cpp.s
.PHONY : src/machine/EnvRegisters.cpp.s

src/machine/Memory.o: src/machine/Memory.cpp.o
.PHONY : src/machine/Memory.o

# target to build an object file
src/machine/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/Memory.cpp.o
.PHONY : src/machine/Memory.cpp.o

src/machine/Memory.i: src/machine/Memory.cpp.i
.PHONY : src/machine/Memory.i

# target to preprocess a source file
src/machine/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/Memory.cpp.i
.PHONY : src/machine/Memory.cpp.i

src/machine/Memory.s: src/machine/Memory.cpp.s
.PHONY : src/machine/Memory.s

# target to generate assembly for a file
src/machine/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/Memory.cpp.s
.PHONY : src/machine/Memory.cpp.s

src/machine/RRegister.o: src/machine/RRegister.cpp.o
.PHONY : src/machine/RRegister.o

# target to build an object file
src/machine/RRegister.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/RRegister.cpp.o
.PHONY : src/machine/RRegister.cpp.o

src/machine/RRegister.i: src/machine/RRegister.cpp.i
.PHONY : src/machine/RRegister.i

# target to preprocess a source file
src/machine/RRegister.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/RRegister.cpp.i
.PHONY : src/machine/RRegister.cpp.i

src/machine/RRegister.s: src/machine/RRegister.cpp.s
.PHONY : src/machine/RRegister.s

# target to generate assembly for a file
src/machine/RRegister.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/RRegister.cpp.s
.PHONY : src/machine/RRegister.cpp.s

src/machine/Register.o: src/machine/Register.cpp.o
.PHONY : src/machine/Register.o

# target to build an object file
src/machine/Register.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/Register.cpp.o
.PHONY : src/machine/Register.cpp.o

src/machine/Register.i: src/machine/Register.cpp.i
.PHONY : src/machine/Register.i

# target to preprocess a source file
src/machine/Register.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/Register.cpp.i
.PHONY : src/machine/Register.cpp.i

src/machine/Register.s: src/machine/Register.cpp.s
.PHONY : src/machine/Register.s

# target to generate assembly for a file
src/machine/Register.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/Register.cpp.s
.PHONY : src/machine/Register.cpp.s

src/machine/VMState.o: src/machine/VMState.cpp.o
.PHONY : src/machine/VMState.o

# target to build an object file
src/machine/VMState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/VMState.cpp.o
.PHONY : src/machine/VMState.cpp.o

src/machine/VMState.i: src/machine/VMState.cpp.i
.PHONY : src/machine/VMState.i

# target to preprocess a source file
src/machine/VMState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/VMState.cpp.i
.PHONY : src/machine/VMState.cpp.i

src/machine/VMState.s: src/machine/VMState.cpp.s
.PHONY : src/machine/VMState.s

# target to generate assembly for a file
src/machine/VMState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/VMState.cpp.s
.PHONY : src/machine/VMState.cpp.s

src/machine/arithmitics/Value.o: src/machine/arithmitics/Value.cpp.o
.PHONY : src/machine/arithmitics/Value.o

# target to build an object file
src/machine/arithmitics/Value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/arithmitics/Value.cpp.o
.PHONY : src/machine/arithmitics/Value.cpp.o

src/machine/arithmitics/Value.i: src/machine/arithmitics/Value.cpp.i
.PHONY : src/machine/arithmitics/Value.i

# target to preprocess a source file
src/machine/arithmitics/Value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/arithmitics/Value.cpp.i
.PHONY : src/machine/arithmitics/Value.cpp.i

src/machine/arithmitics/Value.s: src/machine/arithmitics/Value.cpp.s
.PHONY : src/machine/arithmitics/Value.s

# target to generate assembly for a file
src/machine/arithmitics/Value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/machine/arithmitics/Value.cpp.s
.PHONY : src/machine/arithmitics/Value.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/operands/IOperand.o: src/operands/IOperand.cpp.o
.PHONY : src/operands/IOperand.o

# target to build an object file
src/operands/IOperand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/IOperand.cpp.o
.PHONY : src/operands/IOperand.cpp.o

src/operands/IOperand.i: src/operands/IOperand.cpp.i
.PHONY : src/operands/IOperand.i

# target to preprocess a source file
src/operands/IOperand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/IOperand.cpp.i
.PHONY : src/operands/IOperand.cpp.i

src/operands/IOperand.s: src/operands/IOperand.cpp.s
.PHONY : src/operands/IOperand.s

# target to generate assembly for a file
src/operands/IOperand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/IOperand.cpp.s
.PHONY : src/operands/IOperand.cpp.s

src/operands/ImmediateOperand.o: src/operands/ImmediateOperand.cpp.o
.PHONY : src/operands/ImmediateOperand.o

# target to build an object file
src/operands/ImmediateOperand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/ImmediateOperand.cpp.o
.PHONY : src/operands/ImmediateOperand.cpp.o

src/operands/ImmediateOperand.i: src/operands/ImmediateOperand.cpp.i
.PHONY : src/operands/ImmediateOperand.i

# target to preprocess a source file
src/operands/ImmediateOperand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/ImmediateOperand.cpp.i
.PHONY : src/operands/ImmediateOperand.cpp.i

src/operands/ImmediateOperand.s: src/operands/ImmediateOperand.cpp.s
.PHONY : src/operands/ImmediateOperand.s

# target to generate assembly for a file
src/operands/ImmediateOperand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/ImmediateOperand.cpp.s
.PHONY : src/operands/ImmediateOperand.cpp.s

src/operands/LabelOperand.o: src/operands/LabelOperand.cpp.o
.PHONY : src/operands/LabelOperand.o

# target to build an object file
src/operands/LabelOperand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/LabelOperand.cpp.o
.PHONY : src/operands/LabelOperand.cpp.o

src/operands/LabelOperand.i: src/operands/LabelOperand.cpp.i
.PHONY : src/operands/LabelOperand.i

# target to preprocess a source file
src/operands/LabelOperand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/LabelOperand.cpp.i
.PHONY : src/operands/LabelOperand.cpp.i

src/operands/LabelOperand.s: src/operands/LabelOperand.cpp.s
.PHONY : src/operands/LabelOperand.s

# target to generate assembly for a file
src/operands/LabelOperand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/LabelOperand.cpp.s
.PHONY : src/operands/LabelOperand.cpp.s

src/operands/Memory_AddressOperand.o: src/operands/Memory_AddressOperand.cpp.o
.PHONY : src/operands/Memory_AddressOperand.o

# target to build an object file
src/operands/Memory_AddressOperand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/Memory_AddressOperand.cpp.o
.PHONY : src/operands/Memory_AddressOperand.cpp.o

src/operands/Memory_AddressOperand.i: src/operands/Memory_AddressOperand.cpp.i
.PHONY : src/operands/Memory_AddressOperand.i

# target to preprocess a source file
src/operands/Memory_AddressOperand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/Memory_AddressOperand.cpp.i
.PHONY : src/operands/Memory_AddressOperand.cpp.i

src/operands/Memory_AddressOperand.s: src/operands/Memory_AddressOperand.cpp.s
.PHONY : src/operands/Memory_AddressOperand.s

# target to generate assembly for a file
src/operands/Memory_AddressOperand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/Memory_AddressOperand.cpp.s
.PHONY : src/operands/Memory_AddressOperand.cpp.s

src/operands/RRegOperand.o: src/operands/RRegOperand.cpp.o
.PHONY : src/operands/RRegOperand.o

# target to build an object file
src/operands/RRegOperand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/RRegOperand.cpp.o
.PHONY : src/operands/RRegOperand.cpp.o

src/operands/RRegOperand.i: src/operands/RRegOperand.cpp.i
.PHONY : src/operands/RRegOperand.i

# target to preprocess a source file
src/operands/RRegOperand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/RRegOperand.cpp.i
.PHONY : src/operands/RRegOperand.cpp.i

src/operands/RRegOperand.s: src/operands/RRegOperand.cpp.s
.PHONY : src/operands/RRegOperand.s

# target to generate assembly for a file
src/operands/RRegOperand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/RRegOperand.cpp.s
.PHONY : src/operands/RRegOperand.cpp.s

src/operands/StringLiteralOperand.o: src/operands/StringLiteralOperand.cpp.o
.PHONY : src/operands/StringLiteralOperand.o

# target to build an object file
src/operands/StringLiteralOperand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/StringLiteralOperand.cpp.o
.PHONY : src/operands/StringLiteralOperand.cpp.o

src/operands/StringLiteralOperand.i: src/operands/StringLiteralOperand.cpp.i
.PHONY : src/operands/StringLiteralOperand.i

# target to preprocess a source file
src/operands/StringLiteralOperand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/StringLiteralOperand.cpp.i
.PHONY : src/operands/StringLiteralOperand.cpp.i

src/operands/StringLiteralOperand.s: src/operands/StringLiteralOperand.cpp.s
.PHONY : src/operands/StringLiteralOperand.s

# target to generate assembly for a file
src/operands/StringLiteralOperand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abstract-vm-16bits.dir/build.make CMakeFiles/abstract-vm-16bits.dir/src/operands/StringLiteralOperand.cpp.s
.PHONY : src/operands/StringLiteralOperand.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... abstract-vm-16bits"
	@echo "... generated-sources/VMGrammarBaseListener.o"
	@echo "... generated-sources/VMGrammarBaseListener.i"
	@echo "... generated-sources/VMGrammarBaseListener.s"
	@echo "... generated-sources/VMGrammarBaseVisitor.o"
	@echo "... generated-sources/VMGrammarBaseVisitor.i"
	@echo "... generated-sources/VMGrammarBaseVisitor.s"
	@echo "... generated-sources/VMGrammarLexer.o"
	@echo "... generated-sources/VMGrammarLexer.i"
	@echo "... generated-sources/VMGrammarLexer.s"
	@echo "... generated-sources/VMGrammarListener.o"
	@echo "... generated-sources/VMGrammarListener.i"
	@echo "... generated-sources/VMGrammarListener.s"
	@echo "... generated-sources/VMGrammarParser.o"
	@echo "... generated-sources/VMGrammarParser.i"
	@echo "... generated-sources/VMGrammarParser.s"
	@echo "... generated-sources/VMGrammarVisitor.o"
	@echo "... generated-sources/VMGrammarVisitor.i"
	@echo "... generated-sources/VMGrammarVisitor.s"
	@echo "... src/Program.o"
	@echo "... src/Program.i"
	@echo "... src/Program.s"
	@echo "... src/VM.o"
	@echo "... src/VM.i"
	@echo "... src/VM.s"
	@echo "... src/VMListener.o"
	@echo "... src/VMListener.i"
	@echo "... src/VMListener.s"
	@echo "... src/instructions/ADD.o"
	@echo "... src/instructions/ADD.i"
	@echo "... src/instructions/ADD.s"
	@echo "... src/instructions/ADDSP.o"
	@echo "... src/instructions/ADDSP.i"
	@echo "... src/instructions/ADDSP.s"
	@echo "... src/instructions/BRA.o"
	@echo "... src/instructions/BRA.i"
	@echo "... src/instructions/BRA.s"
	@echo "... src/instructions/BSR.o"
	@echo "... src/instructions/BSR.i"
	@echo "... src/instructions/BSR.s"
	@echo "... src/instructions/Bcc/BEQ.o"
	@echo "... src/instructions/Bcc/BEQ.i"
	@echo "... src/instructions/Bcc/BEQ.s"
	@echo "... src/instructions/Bcc/BGE.o"
	@echo "... src/instructions/Bcc/BGE.i"
	@echo "... src/instructions/Bcc/BGE.s"
	@echo "... src/instructions/Bcc/BGT.o"
	@echo "... src/instructions/Bcc/BGT.i"
	@echo "... src/instructions/Bcc/BGT.s"
	@echo "... src/instructions/Bcc/BLE.o"
	@echo "... src/instructions/Bcc/BLE.i"
	@echo "... src/instructions/Bcc/BLE.s"
	@echo "... src/instructions/Bcc/BLT.o"
	@echo "... src/instructions/Bcc/BLT.i"
	@echo "... src/instructions/Bcc/BLT.s"
	@echo "... src/instructions/Bcc/BNE.o"
	@echo "... src/instructions/Bcc/BNE.i"
	@echo "... src/instructions/Bcc/BNE.s"
	@echo "... src/instructions/Bcc/BOV.o"
	@echo "... src/instructions/Bcc/BOV.i"
	@echo "... src/instructions/Bcc/BOV.s"
	@echo "... src/instructions/CMP.o"
	@echo "... src/instructions/CMP.i"
	@echo "... src/instructions/CMP.s"
	@echo "... src/instructions/DIV.o"
	@echo "... src/instructions/DIV.i"
	@echo "... src/instructions/DIV.s"
	@echo "... src/instructions/ERROR.o"
	@echo "... src/instructions/ERROR.i"
	@echo "... src/instructions/ERROR.s"
	@echo "... src/instructions/HALT.o"
	@echo "... src/instructions/HALT.i"
	@echo "... src/instructions/HALT.s"
	@echo "... src/instructions/IInstruction.o"
	@echo "... src/instructions/IInstruction.i"
	@echo "... src/instructions/IInstruction.s"
	@echo "... src/instructions/LEA.o"
	@echo "... src/instructions/LEA.i"
	@echo "... src/instructions/LEA.s"
	@echo "... src/instructions/LOAD.o"
	@echo "... src/instructions/LOAD.i"
	@echo "... src/instructions/LOAD.s"
	@echo "... src/instructions/Label.o"
	@echo "... src/instructions/Label.i"
	@echo "... src/instructions/Label.s"
	@echo "... src/instructions/MUL.o"
	@echo "... src/instructions/MUL.i"
	@echo "... src/instructions/MUL.s"
	@echo "... src/instructions/NEW.o"
	@echo "... src/instructions/NEW.i"
	@echo "... src/instructions/NEW.s"
	@echo "... src/instructions/OPP.o"
	@echo "... src/instructions/OPP.i"
	@echo "... src/instructions/OPP.s"
	@echo "... src/instructions/PEA.o"
	@echo "... src/instructions/PEA.i"
	@echo "... src/instructions/PEA.s"
	@echo "... src/instructions/POP.o"
	@echo "... src/instructions/POP.i"
	@echo "... src/instructions/POP.s"
	@echo "... src/instructions/PUSH.o"
	@echo "... src/instructions/PUSH.i"
	@echo "... src/instructions/PUSH.s"
	@echo "... src/instructions/QUO.o"
	@echo "... src/instructions/QUO.i"
	@echo "... src/instructions/QUO.s"
	@echo "... src/instructions/REM.o"
	@echo "... src/instructions/REM.i"
	@echo "... src/instructions/REM.s"
	@echo "... src/instructions/RFLOAT.o"
	@echo "... src/instructions/RFLOAT.i"
	@echo "... src/instructions/RFLOAT.s"
	@echo "... src/instructions/RINT.o"
	@echo "... src/instructions/RINT.i"
	@echo "... src/instructions/RINT.s"
	@echo "... src/instructions/RTS.o"
	@echo "... src/instructions/RTS.i"
	@echo "... src/instructions/RTS.s"
	@echo "... src/instructions/STORE.o"
	@echo "... src/instructions/STORE.i"
	@echo "... src/instructions/STORE.s"
	@echo "... src/instructions/SUB.o"
	@echo "... src/instructions/SUB.i"
	@echo "... src/instructions/SUB.s"
	@echo "... src/instructions/SUBSP.o"
	@echo "... src/instructions/SUBSP.i"
	@echo "... src/instructions/SUBSP.s"
	@echo "... src/instructions/Scc/SEQ.o"
	@echo "... src/instructions/Scc/SEQ.i"
	@echo "... src/instructions/Scc/SEQ.s"
	@echo "... src/instructions/Scc/SGE.o"
	@echo "... src/instructions/Scc/SGE.i"
	@echo "... src/instructions/Scc/SGE.s"
	@echo "... src/instructions/Scc/SGT.o"
	@echo "... src/instructions/Scc/SGT.i"
	@echo "... src/instructions/Scc/SGT.s"
	@echo "... src/instructions/Scc/SHL.o"
	@echo "... src/instructions/Scc/SHL.i"
	@echo "... src/instructions/Scc/SHL.s"
	@echo "... src/instructions/Scc/SHR.o"
	@echo "... src/instructions/Scc/SHR.i"
	@echo "... src/instructions/Scc/SHR.s"
	@echo "... src/instructions/Scc/SLE.o"
	@echo "... src/instructions/Scc/SLE.i"
	@echo "... src/instructions/Scc/SLE.s"
	@echo "... src/instructions/Scc/SLT.o"
	@echo "... src/instructions/Scc/SLT.i"
	@echo "... src/instructions/Scc/SLT.s"
	@echo "... src/instructions/Scc/SNE.o"
	@echo "... src/instructions/Scc/SNE.i"
	@echo "... src/instructions/Scc/SNE.s"
	@echo "... src/instructions/Scc/SOV.o"
	@echo "... src/instructions/Scc/SOV.i"
	@echo "... src/instructions/Scc/SOV.s"
	@echo "... src/instructions/TSTO.o"
	@echo "... src/instructions/TSTO.i"
	@echo "... src/instructions/TSTO.s"
	@echo "... src/instructions/WADDR.o"
	@echo "... src/instructions/WADDR.i"
	@echo "... src/instructions/WADDR.s"
	@echo "... src/instructions/WFLOAT.o"
	@echo "... src/instructions/WFLOAT.i"
	@echo "... src/instructions/WFLOAT.s"
	@echo "... src/instructions/WINT.o"
	@echo "... src/instructions/WINT.i"
	@echo "... src/instructions/WINT.s"
	@echo "... src/instructions/WNL.o"
	@echo "... src/instructions/WNL.i"
	@echo "... src/instructions/WNL.s"
	@echo "... src/instructions/WSTR.o"
	@echo "... src/instructions/WSTR.i"
	@echo "... src/instructions/WSTR.s"
	@echo "... src/machine/EnvRegisters.o"
	@echo "... src/machine/EnvRegisters.i"
	@echo "... src/machine/EnvRegisters.s"
	@echo "... src/machine/Memory.o"
	@echo "... src/machine/Memory.i"
	@echo "... src/machine/Memory.s"
	@echo "... src/machine/RRegister.o"
	@echo "... src/machine/RRegister.i"
	@echo "... src/machine/RRegister.s"
	@echo "... src/machine/Register.o"
	@echo "... src/machine/Register.i"
	@echo "... src/machine/Register.s"
	@echo "... src/machine/VMState.o"
	@echo "... src/machine/VMState.i"
	@echo "... src/machine/VMState.s"
	@echo "... src/machine/arithmitics/Value.o"
	@echo "... src/machine/arithmitics/Value.i"
	@echo "... src/machine/arithmitics/Value.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/operands/IOperand.o"
	@echo "... src/operands/IOperand.i"
	@echo "... src/operands/IOperand.s"
	@echo "... src/operands/ImmediateOperand.o"
	@echo "... src/operands/ImmediateOperand.i"
	@echo "... src/operands/ImmediateOperand.s"
	@echo "... src/operands/LabelOperand.o"
	@echo "... src/operands/LabelOperand.i"
	@echo "... src/operands/LabelOperand.s"
	@echo "... src/operands/Memory_AddressOperand.o"
	@echo "... src/operands/Memory_AddressOperand.i"
	@echo "... src/operands/Memory_AddressOperand.s"
	@echo "... src/operands/RRegOperand.o"
	@echo "... src/operands/RRegOperand.i"
	@echo "... src/operands/RRegOperand.s"
	@echo "... src/operands/StringLiteralOperand.o"
	@echo "... src/operands/StringLiteralOperand.i"
	@echo "... src/operands/StringLiteralOperand.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/santourh/abstract-vm-32bits/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

